import { CadDownloadStatus } from '@/models/localStorage/CadDownloadStack';

export const stackList = [
	{
		url: 1701665076943,
		from: 'https://stg0-kr.misumi-ec.com/vona2/detail/110200094770/?HissuCode=TPNC13-3',
		partNumber: 'TPNC13-3',
		index: 0,
		type: 'sinus',
		expiry: 1704257076945,
		requestData: {
			partNumberList: [
				{
					customer_cd: '921997',
					language: 'ko',
					partNumber: 'TPNC13-3',
					seriesCode: '110200094770',
					brdCode: 'MSM1',
					typeCode: 'TPNC',
					SYCD: 'TPNC13-3',
					domain: 'kr',
					environment: 'STG',
					dl_format: '3',
					specValueList: [
						{
							specCADCode: 'A',
							specCADValue: '3',
						},
						{
							specCADCode: 'D',
							specCADValue: '13',
						},
					],
					alterationSpecList: [],
				},
			],
		},
		seriesCode: '110200094770',
		seriesName: '테이퍼핀세트 -부시PL면 장착형',
		id: '2cda687f-3952-4c64-b479-4aae38ed9311123',
		label: '3D | ACIS(sat)',
		fileName: 'TPNC13-3_ACIS(sat)_20231204',
		progress: null,
		created: 1701665076949,
		status: CadDownloadStatus.Done,
		dynamicCadModifiedCommon: {
			pn: 'TPNC13-3',
			ec_loc: '',
			gc_wos: '',
			ge_location: 'asia',
			ge_sdm: '',
			language: 'ko',
			location: '',
			prj: '',
			url: 'https://stg0-kr.misumi-ec.com/vcommon/detail/html/blank.html',
			loggedin: '',
			ms_list: '',
			alterations: '',
			test: '',
			vg: '',
			viewType: '',
			select: '',
			MAIN_PHOTO:
				'//stg0-kr.misumi-ec.com/linked/material/mold/MSM1/PHOTO/10200094770.jpg',
			DOMAIN: 'https://stg0-kr.misumi-ec.com',
			PAGE_PATH:
				'https://stg0-kr.misumi-ec.com/vona2/detail/110200094770/?ProductCode=TPNC13-3',
			BRD_CODE: 'MSM1',
			BRD_NAME: '미스미 (MISUMI)',
			SERIES_CODE: '110200094770',
			SERIES_NAME: '테이퍼핀세트 -부시PL면 장착형',
			customer_cd: '36018974',
			userCode: '36018974',
			PRODUCT_ID: '',
			EST_FLAG: '',
			PRODUCT_TYPE: 'TPNC',
			cgiaction: '',
			downloadflags: '',
			dxfsettings: '',
			format: '',
			part: '',
			firm: 'misumi',
			ok_url:
				'https://stg0-kr.misumi-ec.com/vcommon/detail/html/blank.html?xmlfile=<%download_xml%>',
			Maker: '',
			From: '',
			LogID: '',
			info: '',
			vonaid: '',
			web2cadUrl: '',
			mexUrl: '',
			cadName: '',
			cadGenerationTime: '',
			partcommunityUrl: '',
			partserverUrl: '',
			CombinationView: '',
			environment: 'STG',
			domain: 'kr',
			web2cadParam: {},
			resolveUrl: '',
			assResolveURL: '',
			psConfVonaUrl: '',
			cgi2dviewUrl: '',
			cadenasResolveUrl: '',
			cadenasPsConfVonaUrl: '',
			cadenasCgi2PviewUrl: '',
			cadenasAssistantResolveUrl: '',
			viewerOptions: '',
		},
		version: '',
		downloaded: '1',
		orgSelected: {
			grp: '3D',
			formatText: 'ACIS(sat)',
			formatOthersText: false,
			format: '3',
			formatOthers: 'none',
			version: '',
			versionText: '',
			checkOn: true,
			campaignEndDate: '',
			innerCode: 'MDM00000412758',
			quantity: 1,
			unitPrice: 26520,
			standardUnitPrice: 26520,
			totalPriceIncludingTax: '',
			expressType: '',
			piecesPerPackage: '',
			currencyCode: 'KRW',
			daysToShip: '',
			index: 0,
		},
		checkOnStack: false,
		putsthFlag: false,
		directDown: true,
		// data: {
		// 	status: '201',
		// 	path: 'https://stg.mex.misumi-ec.com/sinus/files/output/cadDownload/TPNC13-3_ACIS(sat)_20231204134445637.zip',
		// 	errorCode: null,
		// 	message: null,
		// 	partNumberList: [
		// 		{
		// 			customer_cd: '921997',
		// 			language: 'ko',
		// 			partNumber: 'TPNC13-3',
		// 			seriesCode: '110200094770',
		// 			brdCode: 'MSM1',
		// 			typeCode: 'TPNC',
		// 			SYCD: 'TPNC13-3',
		// 			domain: 'kr',
		// 			environment: 'STG',
		// 			dl_format: '3',
		// 			specValueList: [
		// 				{
		// 					specCADCode: 'A',
		// 					specCADValue: '3',
		// 				},
		// 				{
		// 					specCADCode: 'D',
		// 					specCADValue: '13',
		// 				},
		// 			],
		// 			alterationSpecList: [],
		// 		},
		// 	],
		// },
		selected: {
			grp: '3D',
			formatText: 'ACIS(sat)',
			formatOthersText: 'false',
			format: '3',
			formatOthers: 'none',
			version: '',
			versionText: '',
			checkOn: true,
			campaignEndDate: '',
			innerCode: 'MDM00000412758',
			quantity: 1,
			unitPrice: 26520,
			standardUnitPrice: 26520,
			totalPriceIncludingTax: '',
			expressType: '',
			piecesPerPackage: '',
			currencyCode: 'KRW',
			daysToShip: '',
			index: 0,
		},
		cadSection: 'PCAD',
		cadFilename:
			'https://stg.mex.misumi-ec.com/sinus/files/output/cadDownload/TPNC13-3_ACIS(sat)_20231204134445637.zip',
		cadFormat: '3',
		cadType: '3D',
		downloadHref:
			'https://stg.mex.misumi-ec.com/sinus/files/output/cadDownload/TPNC13-3_ACIS(sat)_20231204134445637.zip',
		downloadUrl:
			'/vcommon/detail/php/cad_download_name.php?name=TPNC13-3_ACIS(sat)_20231204&url=https%3a%2f%2fstg.mex.misumi-ec.com%2fsinus%2ffiles%2foutput%2fcadDownload%2fTPNC13-3_ACIS(sat)_20231204134445637.zip',
	},
	{
		url: 1701665076943,
		from: 'https://stg0-kr.misumi-ec.com/vona2/detail/110200094770/?HissuCode=TPNC13-3',
		partNumber: 'TPNC13-3',
		index: 0,
		type: 'sinus',
		expiry: 1704257076945,
		requestData: {
			partNumberList: [
				{
					customer_cd: '921997',
					language: 'ko',
					partNumber: 'TPNC13-3',
					seriesCode: '110200094770',
					brdCode: 'MSM1',
					typeCode: 'TPNC',
					SYCD: 'TPNC13-3',
					domain: 'kr',
					environment: 'STG',
					dl_format: '3',
					specValueList: [
						{
							specCADCode: 'A',
							specCADValue: '3',
						},
						{
							specCADCode: 'D',
							specCADValue: '13',
						},
					],
					alterationSpecList: [],
				},
			],
		},
		seriesCode: '110200094770',
		seriesName: '테이퍼핀세트 -부시PL면 장착형',
		id: '2cda687f-3952-4c64-b479-4aae38ed9313433',
		label: '3D | ACIS(sat)',
		fileName: 'TPNC13-3_ACIS(sat)_20231204',
		progress: null,
		created: 1701665076949,
		status: CadDownloadStatus.Putsth,
		dynamicCadModifiedCommon: {
			pn: 'TPNC13-3',
			ec_loc: '',
			gc_wos: '',
			ge_location: 'asia',
			ge_sdm: '',
			language: 'ko',
			location: '',
			prj: '',
			url: 'https://stg0-kr.misumi-ec.com/vcommon/detail/html/blank.html',
			loggedin: '',
			ms_list: '',
			alterations: '',
			test: '',
			vg: '',
			viewType: '',
			select: '',
			MAIN_PHOTO:
				'//stg0-kr.misumi-ec.com/linked/material/mold/MSM1/PHOTO/10200094770.jpg',
			DOMAIN: 'https://stg0-kr.misumi-ec.com',
			PAGE_PATH:
				'https://stg0-kr.misumi-ec.com/vona2/detail/110200094770/?ProductCode=TPNC13-3',
			BRD_CODE: 'MSM1',
			BRD_NAME: '미스미 (MISUMI)',
			SERIES_CODE: '110200094770',
			SERIES_NAME: '테이퍼핀세트 -부시PL면 장착형',
			customer_cd: '36018974',
			userCode: '36018974',
			PRODUCT_ID: '',
			EST_FLAG: '',
			PRODUCT_TYPE: 'TPNC',
			cgiaction: '',
			downloadflags: '',
			dxfsettings: '',
			format: '',
			part: '',
			firm: 'misumi',
			ok_url:
				'https://stg0-kr.misumi-ec.com/vcommon/detail/html/blank.html?xmlfile=<%download_xml%>',
			Maker: '',
			From: '',
			LogID: '',
			info: '',
			vonaid: '',
			web2cadUrl: '',
			mexUrl: '',
			cadName: '',
			cadGenerationTime: '',
			partcommunityUrl: '',
			partserverUrl: '',
			CombinationView: '',
			environment: 'STG',
			domain: 'kr',
			web2cadParam: {},
			resolveUrl: '',
			assResolveURL: '',
			psConfVonaUrl: '',
			cgi2dviewUrl: '',
			cadenasResolveUrl: '',
			cadenasPsConfVonaUrl: '',
			cadenasCgi2PviewUrl: '',
			cadenasAssistantResolveUrl: '',
			viewerOptions: '',
		},
		version: '',
		downloaded: '1',
		orgSelected: {
			grp: '3D',
			formatText: 'ACIS(sat)',
			formatOthersText: false,
			format: '3',
			formatOthers: 'none',
			version: '',
			versionText: '',
			checkOn: true,
			campaignEndDate: '',
			innerCode: 'MDM00000412758',
			quantity: 1,
			unitPrice: 26520,
			standardUnitPrice: 26520,
			totalPriceIncludingTax: '',
			expressType: '',
			piecesPerPackage: '',
			currencyCode: 'KRW',
			daysToShip: '',
			index: 0,
		},
		checkOnStack: false,
		putsthFlag: false,
		directDown: true,
		// data: {
		// 	status: '201',
		// 	path: 'https://stg.mex.misumi-ec.com/sinus/files/output/cadDownload/TPNC13-3_ACIS(sat)_20231204134445637.zip',
		// 	errorCode: null,
		// 	message: null,
		// 	partNumberList: [
		// 		{
		// 			customer_cd: '921997',
		// 			language: 'ko',
		// 			partNumber: 'TPNC13-3',
		// 			seriesCode: '110200094770',
		// 			brdCode: 'MSM1',
		// 			typeCode: 'TPNC',
		// 			SYCD: 'TPNC13-3',
		// 			domain: 'kr',
		// 			environment: 'STG',
		// 			dl_format: '3',
		// 			specValueList: [
		// 				{
		// 					specCADCode: 'A',
		// 					specCADValue: '3',
		// 				},
		// 				{
		// 					specCADCode: 'D',
		// 					specCADValue: '13',
		// 				},
		// 			],
		// 			alterationSpecList: [],
		// 		},
		// 	],
		// },
		selected: {
			grp: '3D',
			formatText: 'ACIS(sat)',
			formatOthersText: 'false',
			format: '3',
			formatOthers: 'none',
			version: '',
			versionText: '',
			checkOn: true,
			campaignEndDate: '',
			innerCode: 'MDM00000412758',
			quantity: 1,
			unitPrice: 26520,
			standardUnitPrice: 26520,
			totalPriceIncludingTax: '',
			expressType: '',
			piecesPerPackage: '',
			currencyCode: 'KRW',
			daysToShip: '',
			index: 0,
		},
		cadSection: 'PCAD',
		cadFilename:
			'https://stg.mex.misumi-ec.com/sinus/files/output/cadDownload/TPNC13-3_ACIS(sat)_20231204134445637.zip',
		cadFormat: '3',
		cadType: '3D',
		downloadHref:
			'https://stg.mex.misumi-ec.com/sinus/files/output/cadDownload/TPNC13-3_ACIS(sat)_20231204134445637.zip',
		downloadUrl:
			'/vcommon/detail/php/cad_download_name.php?name=TPNC13-3_ACIS(sat)_20231204&url=https%3a%2f%2fstg.mex.misumi-ec.com%2fsinus%2ffiles%2foutput%2fcadDownload%2fTPNC13-3_ACIS(sat)_20231204134445637.zip',
	},
	{
		url: 1701665076943,
		from: 'https://stg0-kr.misumi-ec.com/vona2/detail/110200094770/?HissuCode=TPNC13-3',
		partNumber: 'TPNC13-3',
		index: 0,
		type: 'sinus',
		expiry: 1704257076945,
		requestData: {
			partNumberList: [
				{
					customer_cd: '921997',
					language: 'ko',
					partNumber: 'TPNC13-3',
					seriesCode: '110200094770',
					brdCode: 'MSM1',
					typeCode: 'TPNC',
					SYCD: 'TPNC13-3',
					domain: 'kr',
					environment: 'STG',
					dl_format: '3',
					specValueList: [
						{
							specCADCode: 'A',
							specCADValue: '3',
						},
						{
							specCADCode: 'D',
							specCADValue: '13',
						},
					],
					alterationSpecList: [],
				},
			],
		},
		seriesCode: '110200094770',
		seriesName: '테이퍼핀세트 -부시PL면 장착형',
		id: '2cda687f-3952-4c64-b479-4aae3855ed93153',
		label: '3D | ACIS(sat)',
		fileName: 'TPNC13-3_ACIS(sat)_20231204',
		progress: null,
		created: 1701665076949,
		status: CadDownloadStatus.Putsth,
		dynamicCadModifiedCommon: {
			pn: 'TPNC13-3',
			ec_loc: '',
			gc_wos: '',
			ge_location: 'asia',
			ge_sdm: '',
			language: 'ko',
			location: '',
			prj: '',
			url: 'https://stg0-kr.misumi-ec.com/vcommon/detail/html/blank.html',
			loggedin: '',
			ms_list: '',
			alterations: '',
			test: '',
			vg: '',
			viewType: '',
			select: '',
			MAIN_PHOTO:
				'//stg0-kr.misumi-ec.com/linked/material/mold/MSM1/PHOTO/10200094770.jpg',
			DOMAIN: 'https://stg0-kr.misumi-ec.com',
			PAGE_PATH:
				'https://stg0-kr.misumi-ec.com/vona2/detail/110200094770/?ProductCode=TPNC13-3',
			BRD_CODE: 'MSM1',
			BRD_NAME: '미스미 (MISUMI)',
			SERIES_CODE: '110200094770',
			SERIES_NAME: '테이퍼핀세트 -부시PL면 장착형',
			customer_cd: '36018974',
			userCode: '36018974',
			PRODUCT_ID: '',
			EST_FLAG: '',
			PRODUCT_TYPE: 'TPNC',
			cgiaction: '',
			downloadflags: '',
			dxfsettings: '',
			format: '',
			part: '',
			firm: 'misumi',
			ok_url:
				'https://stg0-kr.misumi-ec.com/vcommon/detail/html/blank.html?xmlfile=<%download_xml%>',
			Maker: '',
			From: '',
			LogID: '',
			info: '',
			vonaid: '',
			web2cadUrl: '',
			mexUrl: '',
			cadName: '',
			cadGenerationTime: '',
			partcommunityUrl: '',
			partserverUrl: '',
			CombinationView: '',
			environment: 'STG',
			domain: 'kr',
			web2cadParam: {},
			resolveUrl: '',
			assResolveURL: '',
			psConfVonaUrl: '',
			cgi2dviewUrl: '',
			cadenasResolveUrl: '',
			cadenasPsConfVonaUrl: '',
			cadenasCgi2PviewUrl: '',
			cadenasAssistantResolveUrl: '',
			viewerOptions: '',
		},
		version: '',
		downloaded: '1',
		orgSelected: {
			grp: '3D',
			formatText: 'ACIS(sat)',
			formatOthersText: false,
			format: '3',
			formatOthers: 'none',
			version: '',
			versionText: '',
			checkOn: true,
			campaignEndDate: '',
			innerCode: 'MDM00000412758',
			quantity: 1,
			unitPrice: 26520,
			standardUnitPrice: 26520,
			totalPriceIncludingTax: '',
			expressType: '',
			piecesPerPackage: '',
			currencyCode: 'KRW',
			daysToShip: '',
			index: 0,
		},
		checkOnStack: false,
		putsthFlag: false,
		directDown: true,
		// data: {
		// 	status: '201',
		// 	path: 'https://stg.mex.misumi-ec.com/sinus/files/output/cadDownload/TPNC13-3_ACIS(sat)_20231204134445637.zip',
		// 	errorCode: null,
		// 	message: null,
		// 	partNumberList: [
		// 		{
		// 			customer_cd: '921997',
		// 			language: 'ko',
		// 			partNumber: 'TPNC13-3',
		// 			seriesCode: '110200094770',
		// 			brdCode: 'MSM1',
		// 			typeCode: 'TPNC',
		// 			SYCD: 'TPNC13-3',
		// 			domain: 'kr',
		// 			environment: 'STG',
		// 			dl_format: '3',
		// 			specValueList: [
		// 				{
		// 					specCADCode: 'A',
		// 					specCADValue: '3',
		// 				},
		// 				{
		// 					specCADCode: 'D',
		// 					specCADValue: '13',
		// 				},
		// 			],
		// 			alterationSpecList: [],
		// 		},
		// 	],
		// },
		selected: {
			grp: '3D',
			formatText: 'ACIS(sat)',
			formatOthersText: 'false',
			format: '3',
			formatOthers: 'none',
			version: '',
			versionText: '',
			checkOn: true,
			campaignEndDate: '',
			innerCode: 'MDM00000412758',
			quantity: 1,
			unitPrice: 26520,
			standardUnitPrice: 26520,
			totalPriceIncludingTax: '',
			expressType: '',
			piecesPerPackage: '',
			currencyCode: 'KRW',
			daysToShip: '',
			index: 0,
		},
		cadSection: 'PCAD',
		cadFilename:
			'https://stg.mex.misumi-ec.com/sinus/files/output/cadDownload/TPNC13-3_ACIS(sat)_20231204134445637.zip',
		cadFormat: '3',
		cadType: '3D',
		downloadHref:
			'https://stg.mex.misumi-ec.com/sinus/files/output/cadDownload/TPNC13-3_ACIS(sat)_20231204134445637.zip',
		downloadUrl:
			'/vcommon/detail/php/cad_download_name.php?name=TPNC13-3_ACIS(sat)_20231204&url=https%3a%2f%2fstg.mex.misumi-ec.com%2fsinus%2ffiles%2foutput%2fcadDownload%2fTPNC13-3_ACIS(sat)_20231204134445637.zip',
	},
	{
		url: 1701665076943,
		from: 'https://stg0-kr.misumi-ec.com/vona2/detail/110200094770/?HissuCode=TPNC13-3',
		partNumber: 'TPNC13-3',
		index: 0,
		type: 'sinus',
		expiry: 1704257076945,
		requestData: {
			partNumberList: [
				{
					customer_cd: '921997',
					language: 'ko',
					partNumber: 'TPNC13-3',
					seriesCode: '110200094770',
					brdCode: 'MSM1',
					typeCode: 'TPNC',
					SYCD: 'TPNC13-3',
					domain: 'kr',
					environment: 'STG',
					dl_format: '3',
					specValueList: [
						{
							specCADCode: 'A',
							specCADValue: '3',
						},
						{
							specCADCode: 'D',
							specCADValue: '13',
						},
					],
					alterationSpecList: [],
				},
			],
		},
		seriesCode: '110200094770',
		seriesName: '테이퍼핀세트 -부시PL면 장착형',
		id: '2cda687f-3952-4c64-b479-4aae36788ed93113',
		label: '3D | ACIS(sat)',
		fileName: 'TPNC13-3_ACIS(sat)_20231204',
		progress: null,
		created: 1701665076949,
		status: CadDownloadStatus.Putsth,
		dynamicCadModifiedCommon: {
			pn: 'TPNC13-3',
			ec_loc: '',
			gc_wos: '',
			ge_location: 'asia',
			ge_sdm: '',
			language: 'ko',
			location: '',
			prj: '',
			url: 'https://stg0-kr.misumi-ec.com/vcommon/detail/html/blank.html',
			loggedin: '',
			ms_list: '',
			alterations: '',
			test: '',
			vg: '',
			viewType: '',
			select: '',
			MAIN_PHOTO:
				'//stg0-kr.misumi-ec.com/linked/material/mold/MSM1/PHOTO/10200094770.jpg',
			DOMAIN: 'https://stg0-kr.misumi-ec.com',
			PAGE_PATH:
				'https://stg0-kr.misumi-ec.com/vona2/detail/110200094770/?ProductCode=TPNC13-3',
			BRD_CODE: 'MSM1',
			BRD_NAME: '미스미 (MISUMI)',
			SERIES_CODE: '110200094770',
			SERIES_NAME: '테이퍼핀세트 -부시PL면 장착형',
			customer_cd: '36018974',
			userCode: '36018974',
			PRODUCT_ID: '',
			EST_FLAG: '',
			PRODUCT_TYPE: 'TPNC',
			cgiaction: '',
			downloadflags: '',
			dxfsettings: '',
			format: '',
			part: '',
			firm: 'misumi',
			ok_url:
				'https://stg0-kr.misumi-ec.com/vcommon/detail/html/blank.html?xmlfile=<%download_xml%>',
			Maker: '',
			From: '',
			LogID: '',
			info: '',
			vonaid: '',
			web2cadUrl: '',
			mexUrl: '',
			cadName: '',
			cadGenerationTime: '',
			partcommunityUrl: '',
			partserverUrl: '',
			CombinationView: '',
			environment: 'STG',
			domain: 'kr',
			web2cadParam: {},
			resolveUrl: '',
			assResolveURL: '',
			psConfVonaUrl: '',
			cgi2dviewUrl: '',
			cadenasResolveUrl: '',
			cadenasPsConfVonaUrl: '',
			cadenasCgi2PviewUrl: '',
			cadenasAssistantResolveUrl: '',
			viewerOptions: '',
		},
		version: '',
		downloaded: '1',
		orgSelected: {
			grp: '3D',
			formatText: 'ACIS(sat)',
			formatOthersText: false,
			format: '3',
			formatOthers: 'none',
			version: '',
			versionText: '',
			checkOn: true,
			campaignEndDate: '',
			innerCode: 'MDM00000412758',
			quantity: 1,
			unitPrice: 26520,
			standardUnitPrice: 26520,
			totalPriceIncludingTax: '',
			expressType: '',
			piecesPerPackage: '',
			currencyCode: 'KRW',
			daysToShip: '',
			index: 0,
		},
		checkOnStack: false,
		putsthFlag: false,
		directDown: true,
		// data: {
		// 	status: '201',
		// 	path: 'https://stg.mex.misumi-ec.com/sinus/files/output/cadDownload/TPNC13-3_ACIS(sat)_20231204134445637.zip',
		// 	errorCode: null,
		// 	message: null,
		// 	partNumberList: [
		// 		{
		// 			customer_cd: '921997',
		// 			language: 'ko',
		// 			partNumber: 'TPNC13-3',
		// 			seriesCode: '110200094770',
		// 			brdCode: 'MSM1',
		// 			typeCode: 'TPNC',
		// 			SYCD: 'TPNC13-3',
		// 			domain: 'kr',
		// 			environment: 'STG',
		// 			dl_format: '3',
		// 			specValueList: [
		// 				{
		// 					specCADCode: 'A',
		// 					specCADValue: '3',
		// 				},
		// 				{
		// 					specCADCode: 'D',
		// 					specCADValue: '13',
		// 				},
		// 			],
		// 			alterationSpecList: [],
		// 		},
		// 	],
		// },
		selected: {
			grp: '3D',
			formatText: 'ACIS(sat)',
			formatOthersText: 'false',
			format: '3',
			formatOthers: 'none',
			version: '',
			versionText: '',
			checkOn: true,
			campaignEndDate: '',
			innerCode: 'MDM00000412758',
			quantity: 1,
			unitPrice: 26520,
			standardUnitPrice: 26520,
			totalPriceIncludingTax: '',
			expressType: '',
			piecesPerPackage: '',
			currencyCode: 'KRW',
			daysToShip: '',
			index: 0,
		},
		cadSection: 'PCAD',
		cadFilename:
			'https://stg.mex.misumi-ec.com/sinus/files/output/cadDownload/TPNC13-3_ACIS(sat)_20231204134445637.zip',
		cadFormat: '3',
		cadType: '3D',
		downloadHref:
			'https://stg.mex.misumi-ec.com/sinus/files/output/cadDownload/TPNC13-3_ACIS(sat)_20231204134445637.zip',
		downloadUrl:
			'/vcommon/detail/php/cad_download_name.php?name=TPNC13-3_ACIS(sat)_20231204&url=https%3a%2f%2fstg.mex.misumi-ec.com%2fsinus%2ffiles%2foutput%2fcadDownload%2fTPNC13-3_ACIS(sat)_20231204134445637.zip',
	},
];
