import { Flag } from '@/models/api/Flag';
import {
	AlterationSpec,
	PartNumberSpec,
	SpecViewType,
	SupplementType,
} from '@/models/api/msm/ect/partNumber/SearchPartNumberResponse$search';

export const partNumberSpecMocks: PartNumberSpec[] = [
	{
		specCode: 'typeCode',
		specName: 'type',
		specViewType: '3',
		specValueList: [
			{
				specValue: 'A-SSAL',
				specValueDisp: 'A-SSAL',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: 'A-SSAS',
				specValueDisp: 'A-SSAS',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: 'A-SSHAL',
				specValueDisp: 'A-SSHAL',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: 'SSAL',
				specValueDisp: 'SSAL',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: 'SSAS',
				specValueDisp: 'SSAS',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: 'SSHAL',
				specValueDisp: 'SSHAL',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: 'SSHAS',
				specValueDisp: 'SSHAS',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: 'SSPAS',
				specValueDisp: 'SSPAS',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
		],
	},
	{
		specCode: '00000248945',
		specName: 'Material',
		specViewType: '9',
		openCloseType: '1',
		specNoticeText:
			'Spec notice text. Spec notice text. Spec notice text. Spec notice text. sampletextsampletextsampletextsampletextsampletextsampletextsampletextsampletextsampletextsampletextsampletextsampletextsampletext',
		supplementType: '1',
		specValueList: [
			{
				specValue: 'a',
				specValueDisp: 'SKD11 Equivalent',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: 'b',
				specValueDisp: 'SKH51 Equivalent',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: 'c',
				specValueDisp: 'Powdered high-speed steel',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: 'd',
				specValueDisp: 'D',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: 'e',
				specValueDisp: 'E',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: 'f',
				specValueDisp: 'F',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: 'g',
				specValueDisp: 'G',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: 'h',
				specValueDisp: 'H',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
		],
	},
	{
		specCode: 'jp000264796',
		specName: 'Shank diameter D tolerance',
		specViewType: '4',
		openCloseType: '2',
		supplementType: '1',
		specValueList: [
			{
				specValue: 'mig00000000177481',
				specValueDisp: '+0.005/0',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: 'mig00000000176780',
				specValueDisp: 'm5',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
		],
	},
	{
		specCode: 'jp000264799',
		specName: 'B (Tip length)',
		specViewType: '4',
		openCloseType: '3',
		supplementType: '1',
		specValueList: [
			{
				specValue: 'mig00000000206705',
				specValueDisp: 'L',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: 'mig00000000206818',
				specValueDisp: 'S',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
		],
	},
	{
		specCode: 'jp000264800',
		specName: 'D (Shank diameter)',
		specUnit: 'mm',
		specViewType: '9',
		openCloseType: '3',
		supplementType: '1',
		specValueList: [
			{
				specValue: 'mig00000000176781',
				specValueDisp: '3',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: 'mig00000000176783',
				specValueDisp: '4',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: 'mig00000000176785',
				specValueDisp: '5',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: 'mig00000000176786',
				specValueDisp: '6',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: 'mig00000000176791',
				specValueDisp: '8',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: 'mig00000000176792',
				specValueDisp: '10',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
		],
	},
	{
		specCode: 'jp000496538',
		specName: 'P (Tip dimension)',
		specUnit: 'mm',
		specViewType: SpecViewType.NUMERIC,
		openCloseType: '3',
		supplementType: SupplementType.DRAWING,
		specImageUrl:
			'//stg0-jp.misumi-ec.com/linked/illustration/mech/M0104_C5_F.png',
		numericSpec: {
			hiddenFlag: '0',
			specValueRangeList: [
				{
					minValue: 1,
					maxValue: 9.99,
					stepValue: 0.01,
				},
			],
		},
		specValueList: [],
	},
	{
		specCode: 'jp000264802',
		specName: 'L (L dimension)',
		specUnit: 'mm',
		specViewType: '9',
		openCloseType: '3',
		supplementType: '1',
		numericSpec: {
			hiddenFlag: '0',
			specValueRangeList: [
				{
					minValue: 25,
					maxValue: 40,
					stepValue: 5,
				},
			],
		},
		specValueList: [
			{
				specValue: '25',
				specValueDisp: '25',
				hiddenFlag: '1',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: '30',
				specValueDisp: '30',
				hiddenFlag: '1',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: '35',
				specValueDisp: '35',
				hiddenFlag: '1',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: '40',
				specValueDisp: '40',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
		],
	},
	{
		specCode: '00000627888',
		specName: 'LC (Full length alteration)',
		specUnit: 'mm',
		specViewType: '9',
		openCloseType: '3',
		supplementType: '1',
		numericSpec: {
			hiddenFlag: '0',
			specValueRangeList: [
				{
					minValue: 17,
					maxValue: 39.9,
					stepValue: 0.1,
				},
			],
		},
		specValueList: [],
	},
	{
		specCode: '00000627889',
		specName: 'LCT (Head thickness tolerance change + Total length alteration)',
		specUnit: 'mm',
		specViewType: '9',
		openCloseType: '3',
		supplementType: '1',
		numericSpec: {
			hiddenFlag: '0',
			specValueRangeList: [
				{
					minValue: 17,
					maxValue: 39.9,
					stepValue: 0.1,
				},
			],
		},
		specValueList: [],
	},
	{
		specCode: '00000627890',
		specName: 'LMT (Head thickness tolerance change + Total length alteration)',
		specUnit: 'mm',
		specViewType: '9',
		openCloseType: '3',
		supplementType: '1',
		numericSpec: {
			hiddenFlag: '0',
			specValueRangeList: [
				{
					minValue: 17,
					maxValue: 39.9,
					stepValue: 0.1,
				},
			],
		},
		specValueList: [],
	},
	{
		specCode: '00000627891',
		specName: 'PC (Tip dimension alteration)',
		specUnit: 'mm',
		specViewType: '9',
		openCloseType: '3',
		supplementType: '1',
		numericSpec: {
			hiddenFlag: '0',
			specValueRangeList: [
				{
					minValue: 0.5,
					maxValue: 6.99,
					stepValue: 0.01,
				},
			],
		},
		specValueList: [],
	},
	{
		openCloseType: '3',
		specCode: '00000144105',
		specName: 'Mounting Method',
		specValueList: [
			{
				specValue: 'b',
				specValueDisp: 'Retaining Ring',
				specValueImageUrl:
					'//stg0-my.misumi-ec.com/linked/illustration/mech/M2202_C2_S_b.png',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: 'd',
				specValueDisp: 'Lock Nut (Threaded)',
				specValueImageUrl:
					'//stg0-my.misumi-ec.com/linked/illustration/mech/M2202_C2_S_d.png',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: 'e',
				specValueDisp: 'Tapped',
				specValueImageUrl:
					'//stg0-my.misumi-ec.com/linked/illustration/mech/M2202_C2_S_e.png',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: 'f',
				specValueDisp: 'Set Screw (Set Screw Flat, D-Cut)',
				specValueImageUrl:
					'//stg0-my.misumi-ec.com/linked/illustration/mech/M2202_C2_S_f.png',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
		],
		specViewType: '7',
		supplementType: '4',
	},
	{
		specCode: '00000196582',
		specName: 'Raceway Ring Shape',
		specViewType: '5',
		openCloseType: '3',
		supplementType: '4',
		specValueList: [
			{
				specValue: 'a',
				specValueDisp: 'Ball',
				specValueImageUrl:
					'//stg0-my.misumi-ec.com/linked/illustration/mech/M080201_C3_S_a.png',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: 'l',
				specValueDisp: 'Thrust Ball',
				specValueImageUrl:
					'//stg0-my.misumi-ec.com/linked/illustration/mech/M080201_C3_S_l.png',
				hiddenFlag: '0',
				selectedFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
		],
	},
];

export const alterationSpecList: AlterationSpec[] = [
	{
		specViewType: '9',
		supplementType: '1',
		specCode: '00000651522',
		specName: 'Tip length change [BC]',
		specUnit: 'mm',
		numericSpec: {
			hiddenFlag: '0',
			specValue: '2',
			specValueRangeList: [
				{
					minValue: 2,
					maxValue: 60,
					stepValue: 0.1,
				},
			],
		},
		specValueList: [],
		selectedFlag: '1',
		hiddenFlag: '0',
	},
	{
		specViewType: '9',
		supplementType: '1',
		specCode: '00000651532',
		specName: 'Rounding of tip side edge [PRC]',
		specUnit: 'mm',
		numericSpec: {
			hiddenFlag: '0',
			specValueRangeList: [
				{
					minValue: 0.3,
					maxValue: 1,
					stepValue: 0.1,
				},
			],
		},
		specValueList: [],
		selectedFlag: '0',
		hiddenFlag: '0',
	},
	{
		specViewType: '9',
		supplementType: '1',
		specCode: '00000651530',
		specName: 'Chamfering to tip side edge [PCC]',
		specUnit: 'mm',
		numericSpec: {
			hiddenFlag: '0',
			specValueRangeList: [
				{
					minValue: 0.3,
					maxValue: 1,
					stepValue: 0.1,
				},
			],
		},
		specValueList: [],
		selectedFlag: '0',
		hiddenFlag: '0',
	},
	{
		specViewType: '9',
		supplementType: '1',
		specCode: '00000651523',
		specName: 'Sharp tip angle processing [GC]',
		specUnit: '°',
		numericSpec: {
			hiddenFlag: '0',
			specValueRangeList: [
				{
					minValue: 20,
					maxValue: 89,
					stepValue: 1,
				},
			],
		},
		specValueList: [],
		selectedFlag: '0',
		hiddenFlag: '0',
	},
	{
		specViewType: '4',
		supplementType: '1',
		specCode: '00000651531',
		specName: 'Tip tolerance change',
		numericSpec: {
			specValueRangeList: [],
		},
		specValueList: [
			{
				specValue: 'mig00000009009772',
				specValueDisp: 'PKC',
				hiddenFlag: '0',
				selectedFlag: '0',
				defaultFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
		],
		selectedFlag: '0',
		hiddenFlag: '0',
	},
	{
		specViewType: '3',
		supplementType: '1',
		specCode: '00000651527',
		specName: 'L dimension tolerance',
		numericSpec: {
			specValueRangeList: [],
		},
		specValueList: [
			{
				specValue: 'mig00000009009769',
				specValueDisp: 'LKZ (+0.01/0)',
				hiddenFlag: '0',
				selectedFlag: '0',
				defaultFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: 'mig00000009009768',
				specValueDisp: 'LKC (+0.05/0)',
				hiddenFlag: '0',
				selectedFlag: '0',
				defaultFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
		],
		selectedFlag: '0',
		hiddenFlag: '0',
	},
	{
		specViewType: '9',
		supplementType: '1',
		specCode: '00000651525',
		specName: 'Addition of single key flat to head/position change(KC)',
		numericSpec: {
			specValueRangeList: [],
		},
		specValueList: [
			{
				specValue: 'KC',
				specValueDisp: 'KC',
				hiddenFlag: '0',
				selectedFlag: '0',
				defaultFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
		],
		selectedFlag: '0',
		hiddenFlag: '0',
	},
	{
		specViewType: '4',
		supplementType: '1',
		specCode: '00000651542',
		specName: 'Addition of double key flats to head in parallel',
		numericSpec: {
			specValueRangeList: [],
		},
		specValueList: [
			{
				specValue: 'mig00000009009778',
				specValueDisp: 'WKC',
				hiddenFlag: '0',
				selectedFlag: '0',
				defaultFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
		],
		selectedFlag: '0',
		hiddenFlag: '0',
	},
	{
		specViewType: '9',
		supplementType: '1',
		specCode: '00000651526',
		specName: 'Double key flats at 0゜ and a selected angle [KFC]',
		specUnit: '°',
		numericSpec: {
			hiddenFlag: '0',
			specValueRangeList: [
				{
					minValue: 1,
					maxValue: 359,
					stepValue: 1,
				},
			],
		},
		specValueList: [],
		selectedFlag: '0',
		hiddenFlag: '0',
	},
	{
		specViewType: '9',
		supplementType: '1',
		specCode: '00000651524',
		specName: 'Head diameter change [HC]',
		specUnit: 'mm',
		numericSpec: {
			hiddenFlag: '0',
			specValueRangeList: [
				{
					minValue: 3,
					maxValue: 4.9,
					stepValue: 0.1,
				},
			],
		},
		specValueList: [],
		selectedFlag: '0',
		hiddenFlag: '0',
	},
	{
		specViewType: SpecViewType.NUMERIC,
		supplementType: '1',
		specCode: '00000651538',
		specName: 'Head thickness change [TC]',
		specUnit: 'mm',
		numericSpec: {
			hiddenFlag: '0',
			specValueRangeList: [
				{
					minValue: 2,
					maxValue: 4.9,
					stepValue: 0.1,
				},
			],
		},
		specValueList: [],
		selectedFlag: '0',
		hiddenFlag: '0',
		specNoticeText:
			'Enter the value in the range of 2mm to 4.9mm at 0.1mm intervals.',
	},
	{
		specViewType: '9',
		supplementType: '1',
		specCode: '00000651540',
		specName: 'Head thickness tolerance change',
		specNoticeText:
			'Spec notice text. Spec notice text. Spec notice text. Spec notice text. sampletextsampletextsampletextsampletextsampletext',
		numericSpec: {
			specValueRangeList: [],
		},
		specValueList: [
			{
				specValue: 'mig00000009009777',
				specValueDisp: 'TKM (0/-0.02)',
				hiddenFlag: '0',
				selectedFlag: '0',
				defaultFlag: Flag.TRUE,
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: 'mig00000009009776',
				specValueDisp: 'TKC (+0.02/0)',
				hiddenFlag: '0',
				selectedFlag: '0',
				defaultFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: '1',
				specValueDisp: 'A',
				hiddenFlag: '0',
				selectedFlag: '0',
				defaultFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: '2',
				specValueDisp: 'B',
				hiddenFlag: '0',
				selectedFlag: '0',
				defaultFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: '3',
				specValueDisp: 'C',
				hiddenFlag: '0',
				selectedFlag: '0',
				defaultFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: '4',
				specValueDisp: 'D',
				hiddenFlag: '0',
				selectedFlag: '0',
				defaultFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: '5',
				specValueDisp: 'E',
				hiddenFlag: '0',
				selectedFlag: '0',
				defaultFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
			{
				specValue: '6',
				specValueDisp: 'F',
				hiddenFlag: '0',
				selectedFlag: '0',
				defaultFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
		],
		selectedFlag: '0',
		hiddenFlag: '0',
	},
	{
		specViewType: '9',
		supplementType: '1',
		specCode: '00000651539',
		specName: 'Chamfering of head [TCC]',
		specUnit: 'mm',
		numericSpec: {
			specValueRangeList: [],
		},
		specValueList: [
			{
				specValue: '0.5',
				specValueDisp: '0.5',
				hiddenFlag: '0',
				selectedFlag: '0',
				defaultFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
		],
		selectedFlag: '0',
		hiddenFlag: '0',
	},
	{
		specViewType: '4',
		supplementType: '1',
		specCode: '00000651535',
		specName: 'Head retainer matching processing',
		numericSpec: {
			specValueRangeList: [],
		},
		specValueList: [
			{
				specValue: 'mig00000009009773',
				specValueDisp: 'RC',
				hiddenFlag: '1',
				selectedFlag: '0',
				defaultFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
		],
		selectedFlag: '0',
		hiddenFlag: '1',
	},
	{
		specViewType: '4',
		supplementType: '1',
		specCode: '00000651528',
		specName: 'No shank press-in lead',
		numericSpec: {
			specValueRangeList: [],
		},
		specValueList: [
			{
				specValue: 'mig00000009009770',
				specValueDisp: 'NDC',
				hiddenFlag: '0',
				selectedFlag: '0',
				defaultFlag: '0',
				childSpecValueList: [],
				specValueAttributeList: [],
			},
		],
		selectedFlag: '0',
		hiddenFlag: '0',
	},
];
