import { Category } from '@/models/api/msm/ect/series/SearchSeriesResponse$search';

export const categoryListMock: Category[] = [
	{
		categoryCode: 'M3308010000',
		categoryName: 'Screws for Building Materials',
		seriesCount: 34,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3301110000',
		categoryName: 'Hex Socket Head Cap Screws',
		seriesCount: 32,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M2003060000',
		categoryName: 'Screw Fittings, Screw-In Type Flanges',
		seriesCount: 29,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0114000000',
		categoryName: 'Ball Screw',
		seriesCount: 27,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3301160000',
		categoryName: 'Plastic Screws',
		seriesCount: 27,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3301120000',
		categoryName: 'Hex Socket Set Screws',
		seriesCount: 22,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1001090000',
		categoryName: 'Flexible Shaft Couplings',
		seriesCount: 21,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1606020000',
		categoryName: 'Casters',
		seriesCount: 20,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0301040000',
		categoryName: 'Locating Pins for Jigs and Fixtures',
		seriesCount: 17,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3301060000',
		categoryName: 'Space Saving Bolts',
		seriesCount: 16,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3301150000',
		categoryName: 'Screws with Captured Washer',
		seriesCount: 16,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3301050100',
		categoryName: 'Pan Head Screws',
		seriesCount: 15,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3301070000',
		categoryName: 'Tamper Proof Button Head Cap Screws',
		seriesCount: 13,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3301170000',
		categoryName: 'Self Tapping Screws, Taptite High Tech Screws',
		seriesCount: 13,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0301010000',
		categoryName: 'Locating Pins',
		seriesCount: 12,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0311050000',
		categoryName: 'Clamping Screws',
		seriesCount: 12,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0115050000',
		categoryName: 'Nuts for Lead Screws',
		seriesCount: 11,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3301050200',
		categoryName: 'Flat Head Machine Screws',
		seriesCount: 11,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'E1402020000',
		categoryName: 'Square Connectors',
		seriesCount: 10,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3301020000',
		categoryName: 'Cover Screws',
		seriesCount: 10,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'E1417010000',
		categoryName: 'Screws/Spacers',
		seriesCount: 9,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0507010000',
		categoryName: 'X-Axis',
		seriesCount: 9,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1501070000',
		categoryName: 'Bolts',
		seriesCount: 9,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1716000000',
		categoryName: 'Knobs, Screws',
		seriesCount: 9,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M2004010000',
		categoryName: 'Couplers, One-Touch Joints',
		seriesCount: 8,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'E1413010000',
		categoryName: 'Cable Glands',
		seriesCount: 7,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0115010000',
		categoryName: 'Lead Screws, Nuts',
		seriesCount: 7,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3301100000',
		categoryName: 'Hex Socket Button Head Cap Screws',
		seriesCount: 7,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3301200000',
		categoryName: 'Unified screw, Inch screw',
		seriesCount: 7,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0311010000',
		categoryName: 'Adjustment Screws',
		seriesCount: 6,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1509070000',
		categoryName: '3D Variable Brackets',
		seriesCount: 6,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M2003090000',
		categoryName: 'Fittings for Steel Pipes and Copper Pipes',
		seriesCount: 6,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3301040100',
		categoryName: 'Thumbscrews',
		seriesCount: 6,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3301040200',
		categoryName: 'Ornamental Screws',
		seriesCount: 6,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'E1402030000',
		categoryName: 'Round Connectors',
		seriesCount: 5,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'E1408050000',
		categoryName: 'Metal Tube Options',
		seriesCount: 5,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'E1412020000',
		categoryName: 'Zip Tie Fixtures/Options',
		seriesCount: 5,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0311100000',
		categoryName: 'Stopper Bolts',
		seriesCount: 5,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0507030000',
		categoryName: 'XY-Axis',
		seriesCount: 5,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0509010000',
		categoryName: 'X-Axis',
		seriesCount: 5,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1001070000',
		categoryName: 'Rigid Type',
		seriesCount: 5,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1501080000',
		categoryName: 'Frame Caps',
		seriesCount: 5,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1509020200',
		categoryName: 'Double Post Type',
		seriesCount: 5,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3301190000',
		categoryName: 'Hex Socket Flat Head Cap Screws',
		seriesCount: 5,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3301240000',
		categoryName: 'Screws with Through Hole',
		seriesCount: 5,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'P0302020000',
		categoryName: 'Hexagon Socket Head Cap Screws',
		seriesCount: 5,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'P0302030000',
		categoryName: 'Screw Plugs',
		seriesCount: 5,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'E1402070000',
		categoryName: 'Connectors (Options, Others)',
		seriesCount: 4,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'K1602010000',
		categoryName: 'Screw Maintenance Components',
		seriesCount: 4,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0102000000',
		categoryName: 'Shaft Supports',
		seriesCount: 4,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0103000000',
		categoryName: 'Shaft Collars',
		seriesCount: 4,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0115060000',
		categoryName: 'Lead Screw Support Units',
		seriesCount: 4,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0310010000',
		categoryName: 'Stop Pins, Stopper Bolts',
		seriesCount: 4,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1501020000',
		categoryName: 'Nuts',
		seriesCount: 4,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1501030400',
		categoryName: 'Blind Joint Parts',
		seriesCount: 4,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3301050400',
		categoryName: 'Small Truss Screws',
		seriesCount: 4,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3301140000',
		categoryName:
			'Micro Screws, Pan Head Machine Screws for Precision Instruments',
		seriesCount: 4,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3302010000',
		categoryName: 'Washers',
		seriesCount: 4,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3305010000',
		categoryName: 'Screw Plugs',
		seriesCount: 4,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'T0108040000',
		categoryName: 'Hand Taps',
		seriesCount: 4,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'T0202030100',
		categoryName: 'Clamping Parts (Screw Accessories)',
		seriesCount: 4,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'E1502010000',
		categoryName: 'Exterior Parts',
		seriesCount: 3,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'K1502020000',
		categoryName: 'Suction Bracket',
		seriesCount: 3,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0311060000',
		categoryName: 'Leveling Screws',
		seriesCount: 3,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0311070000',
		categoryName: 'Grub Screws',
		seriesCount: 3,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0402030100',
		categoryName: 'Contact Switches',
		seriesCount: 3,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0602030000',
		categoryName: 'Screw Mounting Type',
		seriesCount: 3,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0802010000',
		categoryName: 'Ball Bearings',
		seriesCount: 3,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0805020000',
		categoryName: 'Flange Type',
		seriesCount: 3,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1509010000',
		categoryName: 'Posts',
		seriesCount: 3,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1608010000',
		categoryName: 'Adjuster',
		seriesCount: 3,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3301130000',
		categoryName: 'Fastening Related Components',
		seriesCount: 3,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3301180000',
		categoryName: 'Self-Drill Screws',
		seriesCount: 3,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3301230000',
		categoryName: 'Small Screws',
		seriesCount: 3,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3302020000',
		categoryName: 'Non-Metal, Plastic',
		seriesCount: 3,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3504020000',
		categoryName: 'Hydraulic Hose Adaptors',
		seriesCount: 3,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'T0202010100',
		categoryName: 'Clamping Parts (for Manual Tightening)',
		seriesCount: 3,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'T0615000000',
		categoryName: 'Screwdriver Bits',
		seriesCount: 3,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'E1414010000',
		categoryName: 'Cable Bushings',
		seriesCount: 2,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'E1502030000',
		categoryName: 'Maintenance Parts',
		seriesCount: 2,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'E3105000000',
		categoryName: 'Terminal Blocks (Round/Y Terminal Types)',
		seriesCount: 2,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'K0801000000',
		categoryName: 'Stop Bolts, Puller Bolts',
		seriesCount: 2,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'K0904040000',
		categoryName: 'Cooling Joint Plugs',
		seriesCount: 2,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'K0905050000',
		categoryName: 'Cooling Pipes',
		seriesCount: 2,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'K1004010000',
		categoryName: 'Screw Plugs',
		seriesCount: 2,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0301020000',
		categoryName: 'Height Adjusting Pins',
		seriesCount: 2,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0805010000',
		categoryName: 'Pillow Type',
		seriesCount: 2,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0805030000',
		categoryName: 'Other Shapes',
		seriesCount: 2,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1105010000',
		categoryName: 'Rollers',
		seriesCount: 2,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1105050000',
		categoryName: 'Pipe Rollers',
		seriesCount: 2,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1107000000',
		categoryName: 'Ball Rollers',
		seriesCount: 2,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1706170000',
		categoryName: 'Cams, Clasps',
		seriesCount: 2,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1905030000',
		categoryName: 'One-Touch Couplings',
		seriesCount: 2,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M2003070000',
		categoryName: 'Hose Fittings',
		seriesCount: 2,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M2202000000',
		categoryName: 'Hinge Pins',
		seriesCount: 2,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3301010100',
		categoryName: 'Wing Hinge Screws',
		seriesCount: 2,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3301030000',
		categoryName: 'Strippers, Reamer Bolts',
		seriesCount: 2,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3301050500',
		categoryName: 'Binding Head Screws',
		seriesCount: 2,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3301080000',
		categoryName: 'Fully Threaded, Stud Bolts',
		seriesCount: 2,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3303010000',
		categoryName: 'Hex Nuts',
		seriesCount: 2,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'T0103030000',
		categoryName: 'Fixtures for Milling Cutter Inserts/Holders',
		seriesCount: 2,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'E1203020000',
		categoryName: 'Fuse Holders',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'E1402040000',
		categoryName: 'Coaxial Connectors',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'E1411060000',
		categoryName: 'Screwdrivers (for Wiring Connections)',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'E1502020000',
		categoryName: 'Interior Parts',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'E1712040000',
		categoryName: 'Image Processing (Options, Others)',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'E3101000000',
		categoryName: 'Interface Terminal Blocks (Round/Y Terminal Types)',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'E3106000000',
		categoryName: 'Terminal Blocks (Rod Terminal Type)',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'K0903010000',
		categoryName: 'Sockets',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'K1004030000',
		categoryName: 'Bolt',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'K1502030000',
		categoryName: 'Angle  Adjustment Bracket',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'K1507070000',
		categoryName: 'Slide Bracket',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0115040000',
		categoryName: 'Slide Screws, Change Nuts',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0118010000',
		categoryName: 'Single Axis Robots',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0119000000',
		categoryName: 'Support Units',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0302020000',
		categoryName: 'Indexing Plungers',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0302060000',
		categoryName: 'Ball Plungers',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0302070000',
		categoryName: 'Roller Plungers',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0303030000',
		categoryName: 'Toggle Clamp Peripheral Components',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0310030000',
		categoryName: 'Stoppers',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0311020000',
		categoryName: 'Threaded Stopper Blocks / Brackets for Stopper Screws',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0314030000',
		categoryName: 'Leading-in / Bushing Clamps',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0401030100',
		categoryName: 'Proximity Sensors',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0502000000',
		categoryName: 'Contact Probes',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0507040000',
		categoryName: 'XZ-Axis',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0507050000',
		categoryName: 'XYZ-Axis',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0507070000',
		categoryName: 'Rotary',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0507110000',
		categoryName: 'Micrometer Heads, Feed Screw',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0509020000',
		categoryName: 'XY-Axis',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0509030000',
		categoryName: 'Z-Axis',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0602010000',
		categoryName: 'Standard Sheath Type',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0807000000',
		categoryName: 'Cam Followers, Roller Followers',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0808000000',
		categoryName: 'Cantilever Shafts',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M0810040000',
		categoryName: 'Bearing Shaft Screws',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1001080000',
		categoryName: 'Universal Joints',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1003020000',
		categoryName: 'Round Belt Pulleys, Idlers',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1301020000',
		categoryName: 'Antivibration Materials',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1309010000',
		categoryName: 'Caps (Round)',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1501110000',
		categoryName: 'Hinges',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1503040000',
		categoryName: 'Casters for Pipe Frame',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1509020400',
		categoryName: 'Strut Clamps Accessories',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1509090000',
		categoryName: 'Accessories',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1608030000',
		categoryName: 'Leveling Mount Related Components',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1715000000',
		categoryName: 'Handle',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1717000000',
		categoryName: 'Lever',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1722000000',
		categoryName: 'Handles',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1723010000',
		categoryName: 'Flat Hinges',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1805020000',
		categoryName: 'Magnets with Holders',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1805100000',
		categoryName: 'Magnets - Screw Mount Type',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1807000000',
		categoryName: 'Dowel Pins, Spring Pins, Stepped Pins',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M1920040000',
		categoryName: 'Floating Joints',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M2003080000',
		categoryName: 'Fittings for Stainless Steel Pipes',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M2003130000',
		categoryName: 'Rotary / Swivel Joints',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M2007020000',
		categoryName: 'Check Valves',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M2007080000',
		categoryName: 'Gate Valves',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M2014060000',
		categoryName: 'Pipe Saddle Clamps',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3301040300',
		categoryName: 'Wing Screws',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3301050600',
		categoryName: 'Upset bolts',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3303120000',
		categoryName: 'Clip Nuts',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3303140000',
		categoryName: 'Cylindrical Nuts',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3303150000',
		categoryName: 'Cap Nuts',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3303170000',
		categoryName: 'Resin Hex Nuts',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3304010000',
		categoryName: 'Tangless Inserts',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'M3310010000',
		categoryName: 'Manual Work Tools',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'P0303050800',
		categoryName: 'Hole Repair Screws',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'T0107010200',
		categoryName: 'Step Drills (Carbide)',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'T0108050000',
		categoryName: 'Taps for Pipes',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'T0112000000',
		categoryName: 'Fixtures Related to Cutting Tools',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'T0315000000',
		categoryName: 'Optical Devices',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'T0405030000',
		categoryName: 'Round Bar Electrodes',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'T0611000000',
		categoryName: 'Tool Sets / Tool Boxes',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'T1905040000',
		categoryName: 'Spatulas/Scrapers',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'T1906100000',
		categoryName: 'Civil Works / Carpentry Components',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'T2202010000',
		categoryName: 'Shackles',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
	{
		categoryCode: 'T2208040000',
		categoryName: 'Table Lifts',
		seriesCount: 1,
		hiddenFlag: '0',
		selectedFlag: '0',
	},
];
