import { ArrayRewriteMethod } from './types';

export const arrayRewriteMethodList: Readonly<ArrayRewriteMethod[]> = [
	ArrayRewriteMethod.OVERWRITE,
	ArrayRewriteMethod.REPLACE,
	ArrayRewriteMethod.CONCAT,
] as const;

export const pathList = [
	'/auth/check',
	'/auth/login',
	'/auth/logout',
	'/banner/search',
	'/batch/',
	'/brand/search',
	'/cad/complete',
	'/cad/download',
	'/cad/preview',
	'/cad/reserve',
	'/cad/termsOfUse',
	'/cadLog/add',
	'/cart/add',
	'/category/relatedSearch',
	'/category/search',
	'/categoryPartNumber/search',
	'/categoryRecommend/search',
	'/chemicalSubstance/search',
	'/chemicalSubstanceLaw',
	'/combo/search',
	'/combo/suggest',
	'/componentParts/search',
	'/customerPartNumber/search',
	'/customerPartNumber/suggest',
	'/dataChecker/search',
	'/faq/search',
	'/feature/search',
	'/featureKeyword/search',
	'/fullText/search$', // $ がないと他のものにもマッチしてしまう
	'/fullText/searchCnavi',
	'/fullText/searchGuide',
	'/fullText/searchInCADComponents',
	'/fullText/searchTech',
	'/fullText/searchTechView',
	'/gear/alteration/search',
	'/gear/layout/calculate',
	'/gear/power/calculate',
	'/gear/search',
	'/gear/strength/calculate',
	'/inner/search',
	'/inquiry/add',
	'/interestRecommend/search',
	'/item/search',
	'/keyword/search',
	'/keyword/suggest$', // $ がないと他のものにもマッチしてしまう
	'/keyword/suggestWithHits',
	'/keywordAction/search',
	'/keywordBanner',
	'/log/add',
	'/menubar/search',
	'/message/search',
	'/modularAssembler/search',
	'/myComponents/add',
	'/orderInfo',
	'/orderedPartNumber/search',
	'/parametricUnit/catalogInfo/search',
	'/parametricUnit/partNumber/search',
	'/paraphraseKeyword/search',
	'/partNumber/search',
	'/partNumber/suggest',
	'/partNumberPreview/search',
	'/price/check',
	'/purchaseRecommend/search',
	'/purchasedConveyor/search',
	'/relatedPartNumber/search',
	'/relatedProductKeyword/search',
	'/relatedSeries/search',
	'/review/search',
	'/review/unReviewedProduct',
	'/searchBoxLink',
	'/searchFeedback/add',
	'/series/search',
	'/similar/reSearch',
	'/similar/seriesList',
	'/similar/specInfo',
	'/similar/specSelectionSearch',
	'/siteFeedback/add',
	'/spell/check',
	'/status/wosStatus',
	'/template',
	'/type/search',
	'/unitLibrary/search',
	'/user$', // $ がないと他のものにもマッチしてしまう
	'/userBanner',
	'/userInfo',
];
